# Generated by Django 4.2.3 on 2023-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_info',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=16)),
                ('exp_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
