# Generated by Django 4.2.3 on 2023-10-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buynow', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
