# Generated by Django 4.2.3 on 2023-10-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='p1',
        ),
    ]
