# Generated by Django 4.2.3 on 2023-10-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_content_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.ImageField(default='', upload_to='shop/videos'),
        ),
    ]
