# Generated by Django 4.2.3 on 2023-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_content_video_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', upload_to='shop/image'),
        ),
    ]
