# Generated by Django 4.2.3 on 2023-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
